version: "3.8"

services:
  backend:
    build:
      context: ./support-sync-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./support-sync-backend:/app
    env_file:
      - ./support-sync-backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./support-sync-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./support-sync-frontend:/app

